import type { AdvancedDomain, AdvancedFeatureStatus, HistoricalAvailability } from "./mlbAdvancedData";

export interface MlbAdvancedFeatureRegistryEntry {
  feature: string; domain: AdvancedDomain; provider: string; canonicalFields: string[];
  status: AdvancedFeatureStatus; sampleRequirement: string; pitSupport: "YES" | "PARTIAL" | "NO";
  historicalAvailability: HistoricalAvailability; currentLiveAvailability: "AVAILABLE" | "PARTIAL" | "UNAVAILABLE";
  modelUsage: "CAPTURED_RESEARCH_ONLY"; fallback: string; version: string;
  stableIdentity: "REQUIRED_AND_PROVEN" | "NOT_REQUIRED" | "NOT_YET_PROVEN";
  evidenceState: "CURRENTLY_CAPTURED_PIT" | "IMMUTABLE_PIT_PROVEN" | "COLLECTOR_READY_NEEDS_OOS" | "NO_CAPTURE";
  eligibilityReasons: string[];
}

const v = "mlb-advanced-research-v1";
export const MLB_ADVANCED_FEATURE_REGISTRY: readonly MlbAdvancedFeatureRegistryEntry[] = [
  { feature: "starter_conventional", domain: "pitcher_conventional", provider: "mlb_stats_api", canonicalFields: ["era","whip","fip","kPct","bbPct","kMinusBbPct","inningsPitched","battersFaced"], status: "CAPTURED_RESEARCH_ONLY", sampleRequirement: "Preserve IP/BF.", pitSupport: "PARTIAL", historicalAvailability: "PARTIAL_HISTORICAL_PIT", currentLiveAvailability: "AVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "Missing remains missing.", version: v, stableIdentity: "NOT_YET_PROVEN", evidenceState: "COLLECTOR_READY_NEEDS_OOS", eligibilityReasons: ["No canonical player mapping audit or full historical PIT capture."] },
  { feature: "probable_starter_identity", domain: "starter_availability", provider: "mlb_stats_api", canonicalFields: ["providerPlayerId","confirmationState","pitchHand"], status: "CAPTURED_RESEARCH_ONLY", sampleRequirement: "N/A", pitSupport: "YES", historicalAvailability: "PARTIAL_HISTORICAL_PIT", currentLiveAvailability: "AVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "UNAVAILABLE, never name-match.", version: v, stableIdentity: "NOT_YET_PROVEN", evidenceState: "COLLECTOR_READY_NEEDS_OOS", eligibilityReasons: ["Provider ID exists but canonical mapping coverage is not yet proven."] },
  { feature: "lineup_identity_order", domain: "lineup", provider: "mlb_stats_api", canonicalFields: ["canonicalPlayerId","battingOrder","confirmedAt"], status: "CAPTURED_RESEARCH_ONLY", sampleRequirement: "Nine mapped hitters.", pitSupport: "YES", historicalAvailability: "PARTIAL_HISTORICAL_PIT", currentLiveAvailability: "PARTIAL", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "Partial revision retained.", version: v, stableIdentity: "NOT_YET_PROVEN", evidenceState: "COLLECTOR_READY_NEEDS_OOS", eligibilityReasons: ["Lineup confirmation and canonical identity are inconsistent; history is partial."] },
  { feature: "bullpen_workload_availability", domain: "bullpen_availability", provider: "mlb_stats_api", canonicalFields: ["pitchesYesterday","pitchesTwoDaysAgo","pitchesThreeDaysAgo","appearancesLast3Days","availabilityState"], status: "CAPTURED_RESEARCH_ONLY", sampleRequirement: "Completed pre-cutoff appearances.", pitSupport: "YES", historicalAvailability: "PARTIAL_HISTORICAL_PIT", currentLiveAvailability: "AVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "UNKNOWN availability.", version: v, stableIdentity: "NOT_YET_PROVEN", evidenceState: "COLLECTOR_READY_NEEDS_OOS", eligibilityReasons: ["Requires mapped reliever coverage and accumulated immutable OOS snapshots."] },
  { feature: "park_run_factor", domain: "park", provider: "internal_park_table", canonicalFields: ["parkFactor","parkFactorVersion"], status: "CAPTURED_RESEARCH_ONLY", sampleRequirement: "Multi-year source table.", pitSupport: "YES", historicalAvailability: "FULL_HISTORICAL_PIT", currentLiveAvailability: "AVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "Explicit fallback recorded.", version: v, stableIdentity: "NOT_REQUIRED", evidenceState: "COLLECTOR_READY_NEEDS_OOS", eligibilityReasons: ["PIT-safe candidate but #214 advanced linked capture/OOS audit has not yet occurred."] },
  { feature: "weather_context", domain: "weather", provider: "open_meteo", canonicalFields: ["temperatureCelsius","windSpeedMph","windDirectionDeg","precipitationMm","isDome"], status: "CAPTURED_RESEARCH_ONLY", sampleRequirement: "Forecast timestamp.", pitSupport: "PARTIAL", historicalAvailability: "NO_RELIABLE_HISTORY", currentLiveAvailability: "AVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "MISSING/NOT_APPLICABLE.", version: v, stableIdentity: "NOT_REQUIRED", evidenceState: "COLLECTOR_READY_NEEDS_OOS", eligibilityReasons: ["Historical forecast PIT is not reliable."] },
  { feature: "league_run_environment", domain: "league_environment", provider: "internal_pit_ledger", canonicalFields: ["runsPerTeamGame","homeRunsPerGame","awayRunsPerGame","sampleGames"], status: "CAPTURED_RESEARCH_ONLY", sampleRequirement: "Completed games before cutoff.", pitSupport: "YES", historicalAvailability: "FULL_HISTORICAL_PIT", currentLiveAvailability: "AVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "UNAVAILABLE with no sample.", version: v, stableIdentity: "NOT_REQUIRED", evidenceState: "IMMUTABLE_PIT_PROVEN", eligibilityReasons: ["Existing #213 chronological ledger is PIT-safe; it is context, not advanced player data."] },
  { feature: "hitter_advanced_metrics", domain: "hitter_conventional", provider: "mlb_stats_api", canonicalFields: ["pa","avg","obp","slg","ops"], status: "PLANNED", sampleRequirement: "PA retained.", pitSupport: "NO", historicalAvailability: "NO_RELIABLE_HISTORY", currentLiveAvailability: "UNAVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "No derivation.", version: v, stableIdentity: "NOT_YET_PROVEN", evidenceState: "NO_CAPTURE", eligibilityReasons: ["No verified player-stat adapter."] },
  { feature: "statcast_expected_metrics", domain: "hitter_conventional", provider: "statcast_adapter_boundary", canonicalFields: ["xera","xwoba","barrelPct","hardHitPct"], status: "NOT_SUPPORTED", sampleRequirement: "Provider-defined.", pitSupport: "NO", historicalAvailability: "NOT_SUPPORTED", currentLiveAvailability: "UNAVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "Never substitute.", version: v, stableIdentity: "NOT_YET_PROVEN", evidenceState: "NO_CAPTURE", eligibilityReasons: ["No approved Statcast adapter."] },
  { feature: "pitch_repertoire_and_matchup", domain: "pitch_repertoire", provider: "statcast_adapter_boundary", canonicalFields: ["pitchType","usagePct","velocity","spin","movement","whiffPct"], status: "NOT_SUPPORTED", sampleRequirement: "Pitch count.", pitSupport: "NO", historicalAvailability: "NOT_SUPPORTED", currentLiveAvailability: "UNAVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "No score.", version: v, stableIdentity: "NOT_YET_PROVEN", evidenceState: "NO_CAPTURE", eligibilityReasons: ["No approved pitch-level adapter."] },
  { feature: "defense_oaa_drs", domain: "defense", provider: "advanced_defense_adapter_boundary", canonicalFields: ["oaa","drs"], status: "NOT_SUPPORTED", sampleRequirement: "Provider-defined.", pitSupport: "NO", historicalAvailability: "NOT_SUPPORTED", currentLiveAvailability: "UNAVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "No rating.", version: v, stableIdentity: "NOT_REQUIRED", evidenceState: "NO_CAPTURE", eligibilityReasons: ["No approved defense provider."] },
  { feature: "baserunning_runs", domain: "baserunning", provider: "baserunning_adapter_boundary", canonicalFields: ["bsr","extraBasesTaken"], status: "NOT_SUPPORTED", sampleRequirement: "Provider-defined.", pitSupport: "NO", historicalAvailability: "NOT_SUPPORTED", currentLiveAvailability: "UNAVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "No steals proxy.", version: v, stableIdentity: "NOT_REQUIRED", evidenceState: "NO_CAPTURE", eligibilityReasons: ["No approved baserunning provider."] },
  { feature: "umpire_effects", domain: "umpire", provider: "umpire_adapter_boundary", canonicalFields: ["homePlateUmpire","assignmentAt"], status: "NOT_SUPPORTED", sampleRequirement: "Pregame assignment.", pitSupport: "NO", historicalAvailability: "NOT_SUPPORTED", currentLiveAvailability: "UNAVAILABLE", modelUsage: "CAPTURED_RESEARCH_ONLY", fallback: "No effect.", version: v, stableIdentity: "NOT_REQUIRED", evidenceState: "NO_CAPTURE", eligibilityReasons: ["No reliable PIT assignment feed."] },
];

export const READY_FOR_215 = MLB_ADVANCED_FEATURE_REGISTRY.filter((f) =>
  f.pitSupport === "YES" && f.currentLiveAvailability === "AVAILABLE"
  && f.historicalAvailability === "FULL_HISTORICAL_PIT"
  && f.stableIdentity !== "NOT_YET_PROVEN"
  && (f.evidenceState === "CURRENTLY_CAPTURED_PIT" || f.evidenceState === "IMMUTABLE_PIT_PROVEN"),
);
export const LIVE_FORWARD_CANDIDATE_NEEDS_OOS = MLB_ADVANCED_FEATURE_REGISTRY.filter((f) => f.evidenceState === "COLLECTOR_READY_NEEDS_OOS");
export const PARTIAL_OR_INCONSISTENT = MLB_ADVANCED_FEATURE_REGISTRY.filter((f) =>
  f.status !== "NOT_SUPPORTED" && f.status !== "PLANNED" && !READY_FOR_215.includes(f) && !LIVE_FORWARD_CANDIDATE_NEEDS_OOS.includes(f),
);
export const NOT_SUPPORTED = MLB_ADVANCED_FEATURE_REGISTRY.filter((f) => f.status === "NOT_SUPPORTED" || f.status === "PLANNED");
/** Compatibility alias; intentionally empty unless strict readiness is met. */
export const MLB_215_READY_FEATURES = READY_FOR_215;
export const MLB_215_UNAVAILABLE_FEATURES = MLB_ADVANCED_FEATURE_REGISTRY.filter((f) => !READY_FOR_215.includes(f));