// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/card-redesign/PickFirst.tsx": () => import("../components/mockups/card-redesign/PickFirst.tsx"),
  "./components/mockups/card-redesign/Signal.tsx": () => import("../components/mockups/card-redesign/Signal.tsx"),
  "./components/mockups/card-redesign/Verdict.tsx": () => import("../components/mockups/card-redesign/Verdict.tsx"),
  "./components/mockups/card-redesign-v2/Current.tsx": () => import("../components/mockups/card-redesign-v2/Current.tsx"),
  "./components/mockups/card-redesign-v2/ScanFirst.tsx": () => import("../components/mockups/card-redesign-v2/ScanFirst.tsx"),
  "./components/mockups/card-redesign-v2/Simplified.tsx": () => import("../components/mockups/card-redesign-v2/Simplified.tsx"),
  "./components/mockups/featured-pick-redesign/Current.tsx": () => import("../components/mockups/featured-pick-redesign/Current.tsx"),
  "./components/mockups/featured-pick-redesign/Simplified.tsx": () => import("../components/mockups/featured-pick-redesign/Simplified.tsx"),
  "./components/mockups/forecast-section/Current.tsx": () => import("../components/mockups/forecast-section/Current.tsx"),
  "./components/mockups/forecast-section/Refined.tsx": () => import("../components/mockups/forecast-section/Refined.tsx"),
  "./components/mockups/results-stats/ResultsStats.tsx": () => import("../components/mockups/results-stats/ResultsStats.tsx"),
  "./components/mockups/tbm-picks/Contender.tsx": () => import("../components/mockups/tbm-picks/Contender.tsx"),
  "./components/mockups/tbm-picks/Premium.tsx": () => import("../components/mockups/tbm-picks/Premium.tsx"),
  "./components/mockups/tbm-picks/Sharp.tsx": () => import("../components/mockups/tbm-picks/Sharp.tsx"),
  "./components/mockups/tbm-picks/Signal.tsx": () => import("../components/mockups/tbm-picks/Signal.tsx")
};
