import {
  boolean,
  check,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  real,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Historical MLB reconstruction ledger. These tables are additive research
 * artifacts only: they are not production predictions and must never be read
 * by the current MLB champion.
 */
export const MLB_HISTORICAL_SCHEMA_VERSION = "mlb-chronological-team-game-v1";
export const MLB_HISTORICAL_CHRONOLOGY_SCHEMA_VERSION = "mlb-completion-chronology-v2";
export const MLB_HISTORICAL_CHRONOLOGY_V3_SCHEMA_VERSION = "mlb-completion-chronology-v3";
export const MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION = "mlb-pitcher-bullpen-pit-v5";
export const MLB_HISTORICAL_EXPECTED_RUNS_SCHEMA_VERSION = "mlb-v4-expected-runs-training-v3";

export const mlbHistoricalArtifactsTable = pgTable("mlb_historical_artifacts", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  sourceManifest: jsonb("source_manifest").notNull(),
  sourceManifestHash: text("source_manifest_hash").notNull(),
  foundationChecksum: text("foundation_checksum").notNull(),
  replayChecksum: text("replay_checksum").notNull(),
  retrievalCutoff: timestamp("retrieval_cutoff", { withTimezone: true }).notNull(),
  status: text("status").notNull(),
  sealedAt: timestamp("sealed_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_artifact_key_idx").on(t.schemaVersion, t.artifactKey),
  uniqueIndex("mlb_historical_artifact_source_hash_idx").on(t.schemaVersion, t.sourceManifestHash),
]);

export const mlbHistoricalGamesTable = pgTable("mlb_historical_games", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_SCHEMA_VERSION),
  canonicalGameId: text("canonical_game_id").notNull(),
  provider: text("provider").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season").notNull(),
  gameType: text("game_type").notNull(),
  gameDate: timestamp("game_date", { withTimezone: true }).notNull(),
  scheduledFirstPitch: timestamp("scheduled_first_pitch", { withTimezone: true }).notNull(),
  actualStartTime: timestamp("actual_start_time", { withTimezone: true }),
  completionTime: timestamp("completion_time", { withTimezone: true }),
  homeProviderTeamId: text("home_provider_team_id").notNull(),
  awayProviderTeamId: text("away_provider_team_id").notNull(),
  homeTeamName: text("home_team_name").notNull(),
  awayTeamName: text("away_team_name").notNull(),
  venueProviderId: text("venue_provider_id"),
  venueName: text("venue_name"),
  homeStarterProviderPlayerId: text("home_starter_provider_player_id"),
  awayStarterProviderPlayerId: text("away_starter_provider_player_id"),
  homeStarterName: text("home_starter_name"),
  awayStarterName: text("away_starter_name"),
  homeStarterState: text("home_starter_state").notNull().default("UNKNOWN"),
  awayStarterState: text("away_starter_state").notNull().default("UNKNOWN"),
  homeRuns: integer("home_runs"),
  awayRuns: integer("away_runs"),
  inningsPlayed: integer("innings_played"),
  gameStatus: text("game_status").notNull(),
  gameNumber: integer("game_number"),
  doubleheaderStatus: text("doubleheader_status").notNull(),
  postseason: boolean("postseason").notNull().default(false),
  neutralSite: boolean("neutral_site").notNull().default(false),
  suspended: boolean("suspended").notNull().default(false),
  resumed: boolean("resumed").notNull().default(false),
  outcomeEligible: boolean("outcome_eligible").notNull().default(false),
  sourcePayloadHash: text("source_payload_hash").notNull(),
  sourceRetrievedAt: timestamp("source_retrieved_at", { withTimezone: true }).notNull(),
  provenance: jsonb("provenance").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_game_provider_identity_idx").on(t.schemaVersion, t.provider, t.providerGameId),
  uniqueIndex("mlb_historical_game_canonical_identity_idx").on(t.schemaVersion, t.canonicalGameId),
  index("mlb_historical_game_chronology_idx").on(t.season, t.scheduledFirstPitch, t.providerGameId),
]);

export const mlbHistoricalTeamIdentityTable = pgTable("mlb_historical_team_identity", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_SCHEMA_VERSION),
  provider: text("provider").notNull(),
  providerTeamId: text("provider_team_id").notNull(),
  season: integer("season").notNull(),
  canonicalTeamId: text("canonical_team_id").notNull(),
  franchiseId: text("franchise_id").notNull(),
  abbreviation: text("abbreviation"),
  providerName: text("provider_name").notNull(),
  resolutionState: text("resolution_state").notNull(),
  resolutionRule: text("resolution_rule").notNull(),
  sourcePayloadHash: text("source_payload_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_team_provider_identity_idx").on(t.schemaVersion, t.provider, t.providerTeamId, t.season),
  index("mlb_historical_team_canonical_idx").on(t.canonicalTeamId, t.season),
]);

export const mlbHistoricalTeamGameRowsTable = pgTable("mlb_historical_team_game_rows", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season").notNull(),
  teamSide: text("team_side").notNull(),
  canonicalTeamId: text("canonical_team_id").notNull(),
  opponentCanonicalTeamId: text("opponent_canonical_team_id").notNull(),
  scheduledFirstPitch: timestamp("scheduled_first_pitch", { withTimezone: true }).notNull(),
  featureCutoff: timestamp("feature_cutoff", { withTimezone: true }),
  starterState: text("starter_state").notNull(),
  lineupState: text("lineup_state").notNull(),
  completionBoundaryState: text("completion_boundary_state").notNull().default("UNVERIFIED"),
  eligibilityState: text("eligibility_state").notNull(),
  /** Deprecated compatibility field. Historical outcomes live in the separate outcome ledger. */
  targets: jsonb("targets").notNull(),
  coreFeatures: jsonb("core_features").notNull(),
  enhancedFeatures: jsonb("enhanced_features").notNull(),
  missingness: jsonb("missingness").notNull(),
  sourceVersions: jsonb("source_versions").notNull(),
  sourceHashes: jsonb("source_hashes").notNull(),
  pitLineage: jsonb("pit_lineage").notNull(),
  quality: jsonb("quality").notNull(),
  checksum: text("checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_team_game_identity_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId, t.teamSide,
  ),
  index("mlb_historical_team_game_chronology_idx").on(t.season, t.scheduledFirstPitch, t.providerGameId),
  index("mlb_historical_team_game_eligibility_idx").on(t.eligibilityState, t.season),
  index("mlb_historical_team_game_checksum_idx").on(t.checksum),
]);

export const mlbHistoricalOutcomesTable = pgTable("mlb_historical_outcomes", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season").notNull(),
  homeRuns: integer("home_runs").notNull(),
  awayRuns: integer("away_runs").notNull(),
  winnerSide: text("winner_side").notNull(),
  runDifference: integer("run_difference").notNull(),
  gameTotal: integer("game_total").notNull(),
  inningsPlayed: integer("innings_played"),
  extraInnings: boolean("extra_innings").notNull(),
  settlementStatus: text("settlement_status").notNull(),
  completionTime: timestamp("completion_time", { withTimezone: true }),
  completionBoundaryState: text("completion_boundary_state").notNull(),
  sourcePayloadHash: text("source_payload_hash").notNull(),
  outcomeHash: text("outcome_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_outcome_game_idx").on(t.schemaVersion, t.artifactKey, t.canonicalGameId),
  index("mlb_historical_outcome_season_idx").on(t.season, t.providerGameId),
]);

export const mlbHistoricalCompletionEvidenceTable = pgTable("mlb_historical_completion_evidence", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_CHRONOLOGY_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  provider: text("provider").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  endpoint: text("endpoint").notNull(),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(),
  scheduledStartTime: timestamp("scheduled_start_time", { withTimezone: true }).notNull(),
  actualStartTime: timestamp("actual_start_time", { withTimezone: true }),
  firstPlayStartTime: timestamp("first_play_start_time", { withTimezone: true }),
  lastPlayStartTime: timestamp("last_play_start_time", { withTimezone: true }),
  lastPlayEndTime: timestamp("last_play_end_time", { withTimezone: true }),
  gameEndTime: timestamp("game_end_time", { withTimezone: true }),
  finalStatusTime: timestamp("final_status_time", { withTimezone: true }),
  providerFinalSeenAt: timestamp("provider_final_seen_at", { withTimezone: true }).notNull(),
  canonicalCompletionTime: timestamp("canonical_completion_time", { withTimezone: true }),
  completionTimeSource: text("completion_time_source").notNull(),
  completionTimeMethod: text("completion_time_method").notNull(),
  completionTimeConfidence: text("completion_time_confidence").notNull(),
  completionTimePrecision: text("completion_time_precision").notNull(),
  featureCutoff: timestamp("feature_cutoff", { withTimezone: true }),
  featureCutoffSource: text("feature_cutoff_source").notNull(),
  featureCutoffConfidence: text("feature_cutoff_confidence").notNull(),
  completionDateEt: date("completion_date_et"),
  gameStatus: text("game_status").notNull(),
  statusCode: text("status_code").notNull(),
  finalStatus: boolean("final_status").notNull(),
  terminalPlayComplete: boolean("terminal_play_complete").notNull(),
  playCount: integer("play_count").notNull(),
  inningsPlayed: integer("innings_played"),
  gameNumber: integer("game_number"),
  doubleheaderStatus: text("doubleheader_status"),
  postponed: boolean("postponed").notNull(),
  suspended: boolean("suspended").notNull(),
  resumed: boolean("resumed").notNull(),
  crossedMidnightUtc: boolean("crossed_midnight_utc").notNull(),
  quarantineReason: text("quarantine_reason"),
  evidencePayload: jsonb("evidence_payload").notNull(),
  rawPayloadHash: text("raw_payload_hash").notNull(),
  evidenceHash: text("evidence_hash").notNull(),
  resolverVersion: text("resolver_version").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_completion_game_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId,
  ),
  uniqueIndex("mlb_historical_completion_provider_idx").on(
    t.schemaVersion, t.artifactKey, t.provider, t.providerGameId,
  ),
  index("mlb_historical_completion_time_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalCompletionTime,
  ),
]);

export const mlbHistoricalRawCompletionSnapshotsTable = pgTable("mlb_historical_raw_completion_snapshots", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_CHRONOLOGY_V3_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  provider: text("provider").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  endpoint: text("endpoint").notNull(),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(),
  httpStatus: integer("http_status").notNull(),
  contentType: text("content_type"),
  rawBody: text("raw_body").notNull(),
  rawBodyHash: text("raw_body_hash").notNull(),
  byteLength: integer("byte_length").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_raw_completion_game_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId,
  ),
  uniqueIndex("mlb_historical_raw_completion_hash_idx").on(
    t.schemaVersion, t.artifactKey, t.rawBodyHash,
  ),
  index("mlb_historical_raw_completion_provider_idx").on(
    t.schemaVersion, t.artifactKey, t.providerGameId,
  ),
]);

export const mlbHistoricalChronologyDecisionsTable = pgTable("mlb_historical_chronology_decisions", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_CHRONOLOGY_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season").notNull(),
  featureCutoff: timestamp("feature_cutoff", { withTimezone: true }),
  featureCutoffSource: text("feature_cutoff_source").notNull(),
  eligiblePriorGameCount: integer("eligible_prior_game_count").notNull(),
  eligiblePriorGameIdsHash: text("eligible_prior_game_ids_hash").notNull(),
  homePriorGameCount: integer("home_prior_game_count").notNull(),
  homePriorGameIdsHash: text("home_prior_game_ids_hash").notNull(),
  awayPriorGameCount: integer("away_prior_game_count").notNull(),
  awayPriorGameIdsHash: text("away_prior_game_ids_hash").notNull(),
  sameDayDecisions: jsonb("same_day_decisions").notNull(),
  deniedReasonCounts: jsonb("denied_reason_counts").notNull(),
  decisionRule: text("decision_rule").notNull(),
  decisionHash: text("decision_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_chronology_decision_game_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId,
  ),
  index("mlb_historical_chronology_decision_season_idx").on(
    t.schemaVersion, t.artifactKey, t.season,
  ),
]);

export const mlbHistoricalExclusionsTable = pgTable("mlb_historical_exclusions", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  provider: text("provider").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season"),
  reasonCode: text("reason_code").notNull(),
  reasonDetail: text("reason_detail").notNull(),
  evidence: jsonb("evidence").notNull(),
  evidenceHash: text("evidence_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_exclusion_identity_idx").on(
    t.schemaVersion, t.artifactKey, t.provider, t.providerGameId, t.reasonCode, t.evidenceHash,
  ),
  index("mlb_historical_exclusion_reason_idx").on(t.reasonCode, t.season),
]);

export const mlbHistoricalSplitsTable = pgTable("mlb_historical_splits", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_SCHEMA_VERSION),
  splitVersion: text("split_version").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  cohort: text("cohort").notNull(),
  assignedAt: timestamp("assigned_at", { withTimezone: true }).notNull(),
  assignmentRule: text("assignment_rule").notNull(),
  immutable: boolean("immutable").notNull().default(true),
  foundationChecksum: text("foundation_checksum").notNull().default("UNBOUND"),
  assignmentHash: text("assignment_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_historical_split_game_idx").on(t.schemaVersion, t.splitVersion, t.canonicalGameId),
  index("mlb_historical_split_cohort_idx").on(t.splitVersion, t.cohort, t.assignedAt),
]);

export const mlbHistoricalRawBoxscoreSnapshotsTable = pgTable("mlb_historical_raw_boxscore_snapshots", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  provider: text("provider").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  endpoint: text("endpoint").notNull(),
  retrievedAt: timestamp("retrieved_at", { withTimezone: true }).notNull(),
  httpStatus: integer("http_status").notNull(),
  contentType: text("content_type"),
  rawBody: text("raw_body").notNull(),
  rawBodyHash: text("raw_body_hash").notNull(),
  byteLength: integer("byte_length").notNull(),
  sourceManifestHash: text("source_manifest_hash").notNull(),
  provenance: jsonb("provenance").notNull(),
  checksum: text("checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_boxscore_game_idx").on(
    t.schemaVersion, t.artifactKey, t.provider, t.providerGameId,
  ),
  uniqueIndex("mlb_hist_boxscore_hash_idx").on(
    t.schemaVersion, t.artifactKey, t.rawBodyHash,
  ),
  index("mlb_hist_boxscore_canonical_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId,
  ),
]);

export const mlbHistoricalPitcherIdentitiesTable = pgTable("mlb_historical_pitcher_identities", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalPitcherId: text("canonical_pitcher_id").notNull(),
  provider: text("provider").notNull(),
  providerPitcherId: text("provider_pitcher_id").notNull(),
  pitcherName: text("pitcher_name").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  canonicalTeamId: text("canonical_team_id").notNull(),
  providerTeamId: text("provider_team_id"),
  throws: text("throws"),
  season: integer("season").notNull(),
  resolutionState: text("resolution_state").notNull(),
  resolutionRule: text("resolution_rule").notNull(),
  ambiguous: boolean("ambiguous").notNull().default(false),
  sourceHashes: jsonb("source_hashes").notNull(),
  provenance: jsonb("provenance").notNull(),
  checksum: text("checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_pitcher_provider_game_idx").on(
    t.schemaVersion, t.artifactKey, t.provider, t.providerPitcherId, t.canonicalGameId,
  ),
  uniqueIndex("mlb_hist_pitcher_canonical_game_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalPitcherId, t.canonicalGameId,
  ),
  index("mlb_hist_pitcher_canonical_idx").on(t.canonicalPitcherId, t.season),
  index("mlb_hist_pitcher_resolution_idx").on(t.resolutionState, t.ambiguous, t.season),
]);

export const mlbHistoricalPitcherAppearancesTable = pgTable("mlb_historical_pitcher_appearances", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season").notNull(),
  canonicalPitcherId: text("canonical_pitcher_id").notNull(),
  providerPitcherId: text("provider_pitcher_id").notNull(),
  canonicalTeamId: text("canonical_team_id").notNull(),
  opponentCanonicalTeamId: text("opponent_canonical_team_id").notNull(),
  appearanceOrder: integer("appearance_order").notNull(),
  starterFlagActual: boolean("starter_flag_actual").notNull(),
  inningsPitched: real("innings_pitched"),
  outsRecorded: integer("outs_recorded"),
  battersFaced: integer("batters_faced"),
  runsAllowed: integer("runs_allowed"),
  earnedRuns: integer("earned_runs"),
  hitsAllowed: integer("hits_allowed"),
  walks: integer("walks"),
  hitBatters: integer("hit_batters"),
  strikeouts: integer("strikeouts"),
  homeRunsAllowed: integer("home_runs_allowed"),
  pitchCount: integer("pitch_count"),
  strikes: integer("strikes"),
  appearanceCompletionTime: timestamp("appearance_completion_time", { withTimezone: true }).notNull(),
  source: text("source").notNull(),
  sourceHash: text("source_hash").notNull(),
  missingness: jsonb("missingness").notNull(),
  provenance: jsonb("provenance").notNull(),
  outcomeChecksum: text("outcome_checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_pitcher_appearance_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId, t.canonicalTeamId,
    t.appearanceOrder,
  ),
  uniqueIndex("mlb_hist_pitcher_game_player_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId, t.canonicalPitcherId,
  ),
  index("mlb_hist_pitcher_appearance_time_idx").on(
    t.canonicalPitcherId, t.appearanceCompletionTime,
  ),
  index("mlb_hist_pitcher_appearance_team_idx").on(
    t.canonicalTeamId, t.season, t.appearanceCompletionTime,
  ),
]);

export const mlbHistoricalBullpenOutcomesTable = pgTable("mlb_historical_bullpen_outcomes", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season").notNull(),
  canonicalTeamId: text("canonical_team_id").notNull(),
  opponentCanonicalTeamId: text("opponent_canonical_team_id").notNull(),
  bullpenInnings: real("bullpen_innings"),
  bullpenOutsRecorded: integer("bullpen_outs_recorded"),
  bullpenBattersFaced: integer("bullpen_batters_faced"),
  bullpenRuns: integer("bullpen_runs"),
  bullpenEarnedRuns: integer("bullpen_earned_runs"),
  bullpenHits: integer("bullpen_hits"),
  bullpenWalks: integer("bullpen_walks"),
  bullpenHitBatters: integer("bullpen_hit_batters"),
  bullpenStrikeouts: integer("bullpen_strikeouts"),
  bullpenHomeRuns: integer("bullpen_home_runs"),
  relieversUsed: integer("relievers_used"),
  bullpenPitchCount: integer("bullpen_pitch_count"),
  bullpenStrikes: integer("bullpen_strikes"),
  highLeverageUsage: jsonb("high_leverage_usage"),
  gameCompletionTime: timestamp("game_completion_time", { withTimezone: true }).notNull(),
  sourceHashes: jsonb("source_hashes").notNull(),
  missingness: jsonb("missingness").notNull(),
  provenance: jsonb("provenance").notNull(),
  outcomeChecksum: text("outcome_checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_bullpen_outcome_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId, t.canonicalTeamId,
  ),
  index("mlb_hist_bullpen_outcome_time_idx").on(
    t.canonicalTeamId, t.gameCompletionTime,
  ),
  index("mlb_hist_bullpen_outcome_season_idx").on(t.season, t.providerGameId),
]);

export const mlbHistoricalPregamePitcherSnapshotsTable = pgTable("mlb_historical_pregame_pitcher_snapshots", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  season: integer("season").notNull(),
  canonicalTeamId: text("canonical_team_id").notNull(),
  opponentCanonicalTeamId: text("opponent_canonical_team_id").notNull(),
  featureCutoff: timestamp("feature_cutoff", { withTimezone: true }).notNull(),
  statThroughTime: timestamp("stat_through_time", { withTimezone: true }),
  pregameStarterId: text("pregame_starter_id"),
  starterIdentityState: text("starter_identity_state").notNull(),
  starterHandedness: text("starter_handedness"),
  starterRoleState: text("starter_role_state").notNull(),
  starterSeasonInnings: real("starter_season_innings"),
  starterSeasonEra: real("starter_season_era"),
  starterSeasonWhip: real("starter_season_whip"),
  starterSeasonKPct: real("starter_season_k_pct"),
  starterSeasonBbPct: real("starter_season_bb_pct"),
  starterSeasonKMinusBbPct: real("starter_season_k_minus_bb_pct"),
  starterSeasonHrRate: real("starter_season_hr_rate"),
  starterSeasonFip: real("starter_season_fip"),
  starterRecentInnings: real("starter_recent_innings"),
  starterRecentEra: real("starter_recent_era"),
  starterRecentWhip: real("starter_recent_whip"),
  starterRecentKPct: real("starter_recent_k_pct"),
  starterRecentBbPct: real("starter_recent_bb_pct"),
  starterDaysRest: integer("starter_days_rest"),
  starterLastStartInnings: real("starter_last_start_innings"),
  starterLastStartPitchCount: integer("starter_last_start_pitch_count"),
  starterRecentWorkload: jsonb("starter_recent_workload").notNull(),
  sourceAppearanceCount: integer("source_appearance_count").notNull(),
  starterSampleSize: integer("starter_sample_size").notNull(),
  starterPriorState: text("starter_prior_state").notNull(),
  starterFeatureCompleteness: real("starter_feature_completeness").notNull(),
  advancedMetricStates: jsonb("advanced_metric_states").notNull(),
  missingness: jsonb("missingness").notNull(),
  provenance: jsonb("provenance").notNull(),
  sourceHashes: jsonb("source_hashes").notNull(),
  checksum: text("checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_pregame_pitcher_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId, t.canonicalTeamId,
  ),
  index("mlb_hist_pregame_pitcher_cutoff_idx").on(
    t.canonicalTeamId, t.featureCutoff,
  ),
  index("mlb_hist_pregame_pitcher_state_idx").on(t.starterIdentityState, t.season),
  index("mlb_hist_pregame_pitcher_checksum_idx").on(t.checksum),
]);

export const mlbHistoricalPregameBullpenSnapshotsTable = pgTable("mlb_historical_pregame_bullpen_snapshots", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  season: integer("season").notNull(),
  canonicalTeamId: text("canonical_team_id").notNull(),
  opponentCanonicalTeamId: text("opponent_canonical_team_id").notNull(),
  featureCutoff: timestamp("feature_cutoff", { withTimezone: true }).notNull(),
  statThroughTime: timestamp("stat_through_time", { withTimezone: true }),
  bullpenSeasonInnings: real("bullpen_season_innings"),
  bullpenSeasonEra: real("bullpen_season_era"),
  bullpenSeasonWhip: real("bullpen_season_whip"),
  bullpenSeasonKPct: real("bullpen_season_k_pct"),
  bullpenSeasonBbPct: real("bullpen_season_bb_pct"),
  bullpenSeasonKMinusBbPct: real("bullpen_season_k_minus_bb_pct"),
  bullpenSeasonHrRate: real("bullpen_season_hr_rate"),
  bullpenSeasonFip: real("bullpen_season_fip"),
  bullpenLast3Innings: real("bullpen_last_3_innings"),
  bullpenLast5Innings: real("bullpen_last_5_innings"),
  bullpenLast10Era: real("bullpen_last_10_era"),
  bullpenPitchesLast1d: integer("bullpen_pitches_last_1d"),
  bullpenPitchesLast2d: integer("bullpen_pitches_last_2d"),
  bullpenPitchesLast3d: integer("bullpen_pitches_last_3d"),
  bullpenInningsLast1d: real("bullpen_innings_last_1d"),
  bullpenInningsLast2d: real("bullpen_innings_last_2d"),
  bullpenInningsLast3d: real("bullpen_innings_last_3d"),
  relieversUsedLast1d: integer("relievers_used_last_1d"),
  relieversUsedLast2d: integer("relievers_used_last_2d"),
  backToBackRelievers: integer("back_to_back_relievers"),
  threeDayRelievers: integer("three_day_relievers"),
  bullpenFatigueState: text("bullpen_fatigue_state").notNull(),
  sourceGameCount: integer("source_game_count").notNull(),
  bullpenSampleSize: integer("bullpen_sample_size").notNull(),
  bullpenPriorState: text("bullpen_prior_state").notNull(),
  bullpenFeatureCompleteness: real("bullpen_feature_completeness").notNull(),
  relieverAvailability: jsonb("reliever_availability").notNull(),
  missingness: jsonb("missingness").notNull(),
  provenance: jsonb("provenance").notNull(),
  sourceHashes: jsonb("source_hashes").notNull(),
  checksum: text("checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_pregame_bullpen_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId, t.canonicalTeamId,
  ),
  index("mlb_hist_pregame_bullpen_cutoff_idx").on(
    t.canonicalTeamId, t.featureCutoff,
  ),
  index("mlb_hist_pregame_bullpen_state_idx").on(t.bullpenFatigueState, t.season),
  index("mlb_hist_pregame_bullpen_checksum_idx").on(t.checksum),
]);

export const mlbHistoricalPitchingEligibilityTable = pgTable("mlb_historical_pitching_eligibility", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_PITCHER_BULLPEN_SCHEMA_VERSION),
  artifactKey: text("artifact_key").notNull(),
  canonicalGameId: text("canonical_game_id").notNull(),
  providerGameId: text("provider_game_id").notNull(),
  season: integer("season").notNull(),
  featureCutoff: timestamp("feature_cutoff", { withTimezone: true }).notNull(),
  coreOffenseEligible: boolean("core_offense_eligible").notNull(),
  pitcherCoreEligible: boolean("pitcher_core_eligible").notNull(),
  bullpenCoreEligible: boolean("bullpen_core_eligible").notNull(),
  fullCoreEligible: boolean("full_core_eligible").notNull(),
  enhancedEligible: boolean("enhanced_eligible").notNull(),
  quarantined: boolean("quarantined").notNull(),
  eligibilityTier: text("eligibility_tier").notNull(),
  reasonCodes: jsonb("reason_codes").notNull(),
  missingness: jsonb("missingness").notNull(),
  provenance: jsonb("provenance").notNull(),
  sourceHashes: jsonb("source_hashes").notNull(),
  checksum: text("checksum").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_pitching_eligibility_game_idx").on(
    t.schemaVersion, t.artifactKey, t.canonicalGameId,
  ),
  index("mlb_hist_pitching_eligibility_tier_idx").on(t.eligibilityTier, t.season),
  index("mlb_hist_pitching_eligibility_flags_idx").on(
    t.pitcherCoreEligible, t.bullpenCoreEligible, t.fullCoreEligible, t.season,
  ),
  index("mlb_hist_pitching_eligibility_checksum_idx").on(t.checksum),
]);

export const mlbHistoricalTrainingManifestsTable = pgTable("mlb_historical_training_manifests", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_EXPECTED_RUNS_SCHEMA_VERSION),
  manifestId: text("manifest_id").notNull(),
  foundationArtifactKey: text("foundation_artifact_key").notNull(),
  foundationHash: text("foundation_hash").notNull(),
  replayHash: text("replay_hash").notNull(),
  sourceManifestHash: text("source_manifest_hash").notNull(),
  splitVersion: text("split_version").notNull(),
  trainGameIds: jsonb("train_game_ids").notNull(),
  validationGameIds: jsonb("validation_game_ids").notNull(),
  oosGameIds: jsonb("oos_game_ids").notNull(),
  trainGameCount: integer("train_game_count").notNull(),
  validationGameCount: integer("validation_game_count").notNull(),
  oosOriginalGameCount: integer("oos_original_game_count").notNull(),
  oosEligibleGameCount: integer("oos_eligible_game_count").notNull(),
  oosExcludedGameCount: integer("oos_excluded_game_count").notNull(),
  oosNewMemberCount: integer("oos_new_member_count").notNull(),
  rejectedCounts: jsonb("rejected_counts").notNull(),
  trainCohortHash: text("train_cohort_hash").notNull(),
  validationCohortHash: text("validation_cohort_hash").notNull(),
  oosCohortHash: text("oos_cohort_hash").notNull(),
  manifestHash: text("manifest_hash").notNull(),
  sealedAt: timestamp("sealed_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_training_manifest_id_idx").on(t.schemaVersion, t.manifestId),
  uniqueIndex("mlb_hist_training_manifest_hash_idx").on(t.schemaVersion, t.manifestHash),
]);

export const mlbHistoricalModelArtifactsTable = pgTable("mlb_historical_model_artifacts", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_EXPECTED_RUNS_SCHEMA_VERSION),
  artifactId: text("artifact_id").notNull(),
  modelId: text("model_id").notNull(),
  modelVersion: text("model_version").notNull(),
  modelState: text("model_state").notNull(),
  modelFamily: text("model_family").notNull(),
  objective: text("objective").notNull(),
  softwareVersion: text("software_version").notNull(),
  randomSeed: integer("random_seed"),
  trainingManifestHash: text("training_manifest_hash").notNull(),
  featureSchema: jsonb("feature_schema").notNull(),
  featureSchemaHash: text("feature_schema_hash").notNull(),
  configuration: jsonb("configuration").notNull(),
  configurationHash: text("configuration_hash").notNull(),
  transforms: jsonb("transforms").notNull(),
  transformsHash: text("transforms_hash").notNull(),
  parameters: jsonb("parameters").notNull(),
  parameterHash: text("parameter_hash").notNull(),
  calibration: jsonb("calibration").notNull(),
  calibrationHash: text("calibration_hash").notNull(),
  distribution: jsonb("distribution").notNull(),
  distributionHash: text("distribution_hash").notNull(),
  artifactHash: text("artifact_hash").notNull(),
  frozenAt: timestamp("frozen_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_model_artifact_id_idx").on(t.schemaVersion, t.artifactId),
  uniqueIndex("mlb_hist_model_version_idx").on(t.schemaVersion, t.modelId, t.modelVersion),
  uniqueIndex("mlb_hist_model_artifact_hash_idx").on(t.schemaVersion, t.artifactHash),
]);

export const mlbHistoricalPreOosLocksTable = pgTable("mlb_historical_pre_oos_locks", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_EXPECTED_RUNS_SCHEMA_VERSION),
  lockId: text("lock_id").notNull(),
  modelId: text("model_id").notNull(),
  modelVersion: text("model_version").notNull(),
  modelState: text("model_state").notNull(),
  modelFamily: text("model_family").notNull(),
  modelArtifactHash: text("model_artifact_hash").notNull(),
  trainingManifestHash: text("training_manifest_hash").notNull(),
  featureSchema: jsonb("feature_schema").notNull(),
  featureSchemaHash: text("feature_schema_hash").notNull(),
  configuration: jsonb("configuration").notNull(),
  configurationHash: text("configuration_hash").notNull(),
  transforms: jsonb("transforms").notNull(),
  transformsHash: text("transforms_hash").notNull(),
  parameters: jsonb("parameters").notNull(),
  parameterHash: text("parameter_hash").notNull(),
  calibration: jsonb("calibration").notNull(),
  calibrationHash: text("calibration_hash").notNull(),
  distribution: jsonb("distribution").notNull(),
  distributionHash: text("distribution_hash").notNull(),
  selectionRule: jsonb("selection_rule").notNull(),
  selectionRuleHash: text("selection_rule_hash").notNull(),
  lockPayload: jsonb("lock_payload").notNull(),
  lockHash: text("lock_hash").notNull(),
  lockedAt: timestamp("locked_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_pre_oos_lock_id_idx").on(t.schemaVersion, t.lockId),
  uniqueIndex("mlb_hist_pre_oos_model_version_idx").on(t.schemaVersion, t.modelId, t.modelVersion),
  uniqueIndex("mlb_hist_pre_oos_lock_hash_idx").on(t.schemaVersion, t.lockHash),
]);

export const mlbHistoricalExpectedRunsForecastsTable = pgTable("mlb_historical_expected_runs_forecasts", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_EXPECTED_RUNS_SCHEMA_VERSION),
  canonicalGameId: text("canonical_game_id").notNull(),
  modelId: text("model_id").notNull(),
  modelVersion: text("model_version").notNull(),
  cohort: text("cohort").notNull(),
  featureSnapshotHash: text("feature_snapshot_hash").notNull(),
  forecastGeneratedAt: timestamp("forecast_generated_at", { withTimezone: true }).notNull(),
  forecastCutoff: timestamp("forecast_cutoff", { withTimezone: true }).notNull(),
  homeExpectedRunsExact: numeric("home_expected_runs_exact", { precision: 20, scale: 10 }).notNull(),
  awayExpectedRunsExact: numeric("away_expected_runs_exact", { precision: 20, scale: 10 }).notNull(),
  projectedTotalExact: numeric("projected_total_exact", { precision: 20, scale: 10 }).notNull(),
  projectedMarginExact: numeric("projected_margin_exact", { precision: 20, scale: 10 }).notNull(),
  homeWinProbability: numeric("home_win_probability", { precision: 20, scale: 15 }).notNull(),
  awayWinProbability: numeric("away_win_probability", { precision: 20, scale: 15 }).notNull(),
  fairHomeMoneyline: numeric("fair_home_moneyline", { precision: 24, scale: 10 }).notNull(),
  fairAwayMoneyline: numeric("fair_away_moneyline", { precision: 24, scale: 10 }).notNull(),
  calibrationVersion: text("calibration_version").notNull(),
  distributionVersion: text("distribution_version").notNull(),
  trainingManifestHash: text("training_manifest_hash").notNull(),
  parameterHash: text("parameter_hash").notNull(),
  calibrationHash: text("calibration_hash").notNull(),
  distributionHash: text("distribution_hash").notNull(),
  forecastHash: text("forecast_hash").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_expected_runs_game_model_idx").on(
    t.schemaVersion, t.canonicalGameId, t.modelId, t.modelVersion,
  ),
  uniqueIndex("mlb_hist_expected_runs_forecast_hash_idx").on(t.schemaVersion, t.forecastHash),
  index("mlb_hist_expected_runs_cohort_idx").on(t.modelId, t.modelVersion, t.cohort),
]);

export const mlbHistoricalEvaluationRunsTable = pgTable("mlb_historical_evaluation_runs", {
  id: serial("id").primaryKey(),
  schemaVersion: text("schema_version").notNull().default(MLB_HISTORICAL_EXPECTED_RUNS_SCHEMA_VERSION),
  evaluationRunId: text("evaluation_run_id").notNull(),
  modelId: text("model_id").notNull(),
  modelVersion: text("model_version").notNull(),
  phase: text("phase").notNull(),
  cohort: text("cohort").notNull(),
  foldIdentity: text("fold_identity").notNull(),
  gameCount: integer("game_count").notNull(),
  trainingManifestHash: text("training_manifest_hash").notNull(),
  modelArtifactHash: text("model_artifact_hash").notNull(),
  forecastSetHash: text("forecast_set_hash").notNull(),
  metrics: jsonb("metrics").notNull(),
  segments: jsonb("segments").notNull(),
  baselines: jsonb("baselines").notNull(),
  integrity: jsonb("integrity").notNull(),
  checksum: text("checksum").notNull(),
  evaluatedAt: timestamp("evaluated_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("mlb_hist_evaluation_run_identity_idx").on(
    t.schemaVersion, t.modelId, t.modelVersion, t.phase, t.evaluationRunId,
  ),
  uniqueIndex("mlb_hist_evaluation_checksum_idx").on(t.schemaVersion, t.checksum),
  uniqueIndex("mlb_hist_one_locked_oos_idx")
    .on(t.schemaVersion, t.modelId, t.modelVersion)
    .where(sql`${t.phase} = 'LOCKED_OOS'`),
  index("mlb_hist_evaluation_phase_idx").on(t.phase, t.modelId, t.modelVersion),
  check(
    "mlb_hist_evaluation_phase_check",
    sql`${t.phase} IN ('TRAIN', 'VALIDATION', 'WALK_FORWARD', 'LOCKED_OOS')`,
  ),
]);

export type MlbHistoricalGame = typeof mlbHistoricalGamesTable.$inferSelect;
export type InsertMlbHistoricalGame = typeof mlbHistoricalGamesTable.$inferInsert;
export type MlbHistoricalTeamGameRow = typeof mlbHistoricalTeamGameRowsTable.$inferSelect;
export type InsertMlbHistoricalTeamGameRow = typeof mlbHistoricalTeamGameRowsTable.$inferInsert;
export type MlbHistoricalPitcherAppearance = typeof mlbHistoricalPitcherAppearancesTable.$inferSelect;
export type InsertMlbHistoricalPitcherAppearance = typeof mlbHistoricalPitcherAppearancesTable.$inferInsert;
export type MlbHistoricalPregamePitcherSnapshot = typeof mlbHistoricalPregamePitcherSnapshotsTable.$inferSelect;
export type InsertMlbHistoricalPregamePitcherSnapshot = typeof mlbHistoricalPregamePitcherSnapshotsTable.$inferInsert;
export type MlbHistoricalPregameBullpenSnapshot = typeof mlbHistoricalPregameBullpenSnapshotsTable.$inferSelect;
export type InsertMlbHistoricalPregameBullpenSnapshot = typeof mlbHistoricalPregameBullpenSnapshotsTable.$inferInsert;
export type MlbHistoricalTrainingManifest = typeof mlbHistoricalTrainingManifestsTable.$inferSelect;
export type InsertMlbHistoricalTrainingManifest = typeof mlbHistoricalTrainingManifestsTable.$inferInsert;
export type MlbHistoricalModelArtifact = typeof mlbHistoricalModelArtifactsTable.$inferSelect;
export type InsertMlbHistoricalModelArtifact = typeof mlbHistoricalModelArtifactsTable.$inferInsert;
export type MlbHistoricalPreOosLock = typeof mlbHistoricalPreOosLocksTable.$inferSelect;
export type InsertMlbHistoricalPreOosLock = typeof mlbHistoricalPreOosLocksTable.$inferInsert;
export type MlbHistoricalExpectedRunsForecast = typeof mlbHistoricalExpectedRunsForecastsTable.$inferSelect;
export type InsertMlbHistoricalExpectedRunsForecast = typeof mlbHistoricalExpectedRunsForecastsTable.$inferInsert;
export type MlbHistoricalEvaluationRun = typeof mlbHistoricalEvaluationRunsTable.$inferSelect;
export type InsertMlbHistoricalEvaluationRun = typeof mlbHistoricalEvaluationRunsTable.$inferInsert;